from fastapi import FastAPI, HTTPException, File, UploadFile, Form, Depends
from app.schemas import PostCreate, PostResponse, UserCreate, UserRead, UserUpdate
from app.db import Post, create_db_and_tables, get_async_session, User
from sqlalchemy.ext.asyncio import AsyncSession
from contextlib import asynccontextmanager
from sqlalchemy import select
from app.images import imagekit
import shutil
import os
import uuid
import tempfile
from PIL import Image, ImageOps
from app.users import auth_backend, current_active_user, fastapi_users


VIDEO_EXTENSIONS = {".mp4", ".webm", ".mov", ".m4v", ".avi", ".mkv", ".ogv"}
IMAGE_EXTENSIONS = {
    ".jpg",
    ".jpeg",
    ".png",
    ".webp",
    ".gif",
    ".bmp",
    ".tif",
    ".tiff",
    ".avif",
}


def detect_media_type(upload_file: UploadFile) -> str:
    content_type = (upload_file.content_type or "").lower()
    extension = os.path.splitext(upload_file.filename or "")[1].lower()

    if content_type.startswith("video/") or extension in VIDEO_EXTENSIONS:
        return "video"
    if content_type.startswith("image/") or extension in IMAGE_EXTENSIONS:
        return "image"
    return "unknown"


# Runs once at startup
# Creates the database tables if they don't exist
@asynccontextmanager
async def lifespan(app: FastAPI):
    await create_db_and_tables()
    yield


# Registers the lifespan with the FastAPI app
app = FastAPI(lifespan=lifespan)

# Include auth routes (login/logout) - auto-generated by FastAPI Users
# Routes: POST /auth/jwt/login, POST /auth/jwt/logout
app.include_router(
    fastapi_users.get_auth_router(auth_backend), prefix="/auth/jwt", tags=["auth"]
)

# Include register route - auto-generated by FastAPI Users
# Route: POST /auth/register
app.include_router(
    fastapi_users.get_register_router(UserRead, UserCreate),
    prefix="/auth",
    tags=["auth"],
)

# Include password reset routes - auto-generated by FastAPI Users
# Routes: POST /auth/forgot-password, POST /auth/reset-password
app.include_router(
    fastapi_users.get_reset_password_router(), prefix="/auth", tags=["auth"]
)

# Include email verification routes - auto-generated by FastAPI Users
# Routes: POST /auth/request-verify-token, POST /auth/verify
app.include_router(
    fastapi_users.get_verify_router(UserRead), prefix="/auth", tags=["auth"]
)

# Include user management routes - auto-generated by FastAPI Users
# Routes: GET /users/me, GET /users/{id}, PATCH /users/me, PATCH /users/{id}, DELETE /users/{id}
app.include_router(
    fastapi_users.get_users_router(UserRead, UserUpdate),
    prefix="/users",
    tags=["users"],
)


# Accepts a file + caption, uploads the file to ImageKit, and saves a DB row.
# Requires authentication (only logged-in users can upload)
@app.post("/upload")
async def upload_file(
    file: UploadFile = File(...),
    caption: str = Form(""),
    user: User = Depends(current_active_user),
    session: AsyncSession = Depends(get_async_session),
):

    temp_file_path = None
    processed_file_path = None
    media_type = detect_media_type(file)

    try:
        if media_type == "unknown":
            raise HTTPException(
                status_code=400,
                detail="Only image and video files are supported.",
            )

        # Create a temporary file to hold the uploaded content
        with tempfile.NamedTemporaryFile(
            delete=False, suffix=os.path.splitext(file.filename or "")[1]
        ) as temp_file:
            temp_file_path = temp_file.name
            shutil.copyfileobj(file.file, temp_file)
        upload_file_name = file.filename or "upload"

        if media_type == "image":
            with Image.open(temp_file_path) as img:
                image = ImageOps.exif_transpose(img)
                width, height = image.size
                total_pixels = width * height

                max_pixels = 24_000_000
                if total_pixels > max_pixels:
                    scale = (max_pixels / total_pixels) ** 0.5
                    new_size = (
                        max(1, int(width * scale)),
                        max(1, int(height * scale)),
                    )
                    resized = image.resize(new_size, Image.Resampling.LANCZOS)

                    if resized.mode not in ("RGB", "L"):
                        resized = resized.convert("RGB")

                    with tempfile.NamedTemporaryFile(delete=False, suffix=".jpg") as processed_file:
                        processed_file_path = processed_file.name

                    resized.save(
                        processed_file_path,
                        format="JPEG",
                        quality=90,
                        optimize=True,
                    )
                    upload_file_name = f"{os.path.splitext(upload_file_name)[0]}-optimized.jpg"

        source_path = processed_file_path or temp_file_path

        with open(source_path, "rb") as upload_file:

            # Upload to ImageKit
            upload_result = imagekit.files.upload(
                file=upload_file,
                file_name=upload_file_name,
                use_unique_file_name=True,
                tags=["backend-upload"],
            )

            # Validate upload
        if not upload_result.url:
            raise HTTPException(status_code=502, detail="Upload failed")

        # Save DB record
        post = Post(
            user_id=user.id,
            caption=caption,
            url=upload_result.url,
            file_type=media_type,
            file_name=upload_result.name or file.filename,
        )
        session.add(post)
        await session.commit()
        await session.refresh(post)
        return post
    except Exception as e:
        error_message = str(e)
        normalized_error = error_message.lower()

        if "ELIMIT" in error_message and "resolution limit" in error_message:
            raise HTTPException(
                status_code=400,
                detail="Image is too large. Please upload a smaller image (under 25 megapixels).",
            )
        if "size" in normalized_error and (
            "limit" in normalized_error or "exceed" in normalized_error
        ):
            raise HTTPException(
                status_code=400,
                detail="File is too large. Please upload a smaller image or video.",
            )
        raise HTTPException(status_code=500, detail=error_message)
    finally:
        # Clean up temp file
        if temp_file_path and os.path.exists(temp_file_path):
            os.unlink(temp_file_path)
        if processed_file_path and os.path.exists(processed_file_path):
            os.unlink(processed_file_path)
        file.file.close()


# Fetches posts from DB in newest-first order
@app.get("/feed")
async def get_feed(
    session: AsyncSession = Depends(get_async_session),
    user: User = Depends(current_active_user),
):
    result = await session.execute(select(Post).order_by(Post.created_at.desc()))

    posts = [row[0] for row in result.all()]

    result = await session.execute(select(User))
    users = [row[0] for row in result.all()]
    user_dict = {u.id: u.email for u in users}

    posts_data = []
    # Builds JSON Manually
    for post in posts:
        posts_data.append(
            {
                "id": str(post.id),
                "user_id": str(post.user_id),
                "caption": post.caption,
                "url": post.url,
                "file_type": post.file_type,
                "file_name": post.file_name,
                "created_at": post.created_at.isoformat(),
                "is_owner": post.user_id == user.id,
                "email": user_dict.get(post.user_id, "Unknown"),
            }
        )
    return {"posts": posts_data}


@app.delete("/posts/{post_id}")
async def delete_post(
    post_id: str,
    session: AsyncSession = Depends(get_async_session),
    user: User = Depends(current_active_user),
):
    try:
        # Conver the string ID to UUID
        post_uuid = uuid.UUID(post_id)

        # Query the database for the post with this UUID
        result = await session.execute(select(Post).where(Post.id == post_uuid))

        # Extract the first Post object from the result (or None if not found)
        post = result.scalar_one_or_none()

        if not post:
            raise HTTPException(status_code=404, detail="Post not found")

        if str(post.user_id) != str(user.id):
            raise HTTPException(
                status_code=403, detail="You don't have permission to delete this post"
            )

        # Delete the post from the database
        await session.delete(post)

        # Commit the transaction to make the deletion permanent
        await session.commit()
        return {"success": True, "message": "Post deleted successfully"}
    except Exception as e:
        raise HTTPException(status_code=500, detail=str(e))
